---
name: idr0056-stojic-lncrnas/screenA
version: 1

defaults:
    # Should the column be processed when creating bulk-annotations (yes/no)
    include: no
    # Columns type of the bulk-annotations column
    type: string

    # If non-empty a string used to separate multiple fields in a column
    # White space will be stripped
    split: ,
    # Should this column be included in the clients (yes/no)
    includeclient: yes
    # Should this column be visible in the clients, if no the column should be
    # hidden in the client but will still be indexed by the searcher (yes/no)
    visible: yes
    # Should empty values be omitted from the client display
    omitempty: yes

columns:

  - name: Sequence_1
    include: yes
  - name: Sequence_2
    include: yes
  - name: Sequence_3
    include: yes
  - name: Sequence_4
    include: yes
  - name: Reagent Design Gene Annotation Build
    clientname: Gene Annotation Build
    include: yes
  - name: Control Type
    include: yes
  - name: Control Comments
    include: yes
  - name: Comments
    include: yes


######################################################################
# mapr groups
######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
      - name: Characteristics [Organism]
        clientname: Organism
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
      - name: Characteristics [Cell Line or Strain]
        clientname: Cell Line
        include: yes

  - group:
      namespace: openmicroscopy.org/mapr/gene
      columns:
      - name: Gene Identifier
        include: yes
        omitempty: no
      - name: Gene Identifier
        clientname: Gene Identifier URL
        clientvalue: https://www.ncbi.nlm.nih.gov/gene/?term={{ value|urlencode }}
        include: yes
      - name: Gene Symbol
        include: yes
        omitempty: no


# Advanced options (experimental)
advanced:
    # If a map-annotation is attached to a well also attach it to all images
    # in the well
    well_to_images: yes

    # TODO: Primary key config should be in a global config
    ignore_missing_primary_key: yes
    primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
      - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
      - Cell Line
    - namespace: openmicroscopy.org/mapr/gene
      keys:
      - Gene Identifier
      - Gene Symbol
